name: Fastlane test build

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch'     
        required: false
        default: 'Batvos-patch-1-1'

jobs:
  main:
    runs-on: macos-11
    timeout-minutes: 20

    strategy:
      matrix:
        scheme:
          - Anytype
        product-name:
          - Anytype

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Install SSH key for access to repository.
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY_FASTLANE_COMMIT }}

      - name: Setup ruby
        uses: ruby/setup-ruby@v1.81.0
        with:
          ruby-version: 2.7.2
          bundler-cache: true

      - uses: maxim-lobanov/setup-xcode@v1.3.0
        with:
          xcode-version: '13.0'
          
      - name: Toolchain
        run: |
            swift --version
            xcrun --find swift
        

      - name: Download Middleware
        run: ruby ./Scripts/middleware_for_ci.rb --token ${{ secrets.ANYTYPE_MIDDLEWARE_ACCESS_TOKEN }}

#       - name: Build
#         run: |
#           export LC_ALL=en_US.UTF-8
#           export LANG=en_US.UTF-8
#           bundle exec fastlane test_build
#         env:
#           MATCH_GIT_PRIVATE_KEY: ${{ secrets.SSH_KEY_FASTLANE_MATCH }}
#           MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
#           APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
#           APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}
#           APP_STORE_CONNECT_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_PRIVATE_KEY }}
